Cluster management views
kubefirst/console pull request #221
Opened 2023-08-01 01:08 UTC by D-B-Hawk

2023-08-01 14:02 UTC, CristhianF7 requested changes
Let me know if you have any questions

2023-08-01 14:02 UTC, CristhianF7 commented on containers/services/index.tsx
> -import React, { FunctionComponent, useEffect, useCallback, useState, useMemo } from 'react';
Hey @D-B-Hawk, this is great. The services page is a different page so I think you need to move these changes to the cluster-management page

2023-08-01 21:44 UTC, D-B-Hawk commented on containers/services/index.tsx
> -import React, { FunctionComponent, useEffect, useCallback, useState, useMemo } from 'react';
🙃

2023-08-02 22:15 UTC, CristhianF7 approved these changes

2023-08-03 01:20 UTC, closed without merging